import "bootstrap/dist/css/bootstrap.min.css";
import StoreProvider from "./StoreProvider";
import Header from "@/Components/Header/Header";
import "./global.css"
import Hero from "@/Components/Hero/Hero";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
        </body>
    </html>
  );
}
